# Generated by carnix 0.10.0: carnix generate-nix --standalone --src ./.
with import <nixpkgs> {};
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
  cratesIO = (callPackage ./crates-io.nix { });
in
rec {
  crates = cratesIO // rec {
# hello-1.0.0

    crates.hello."1.0.0" = deps: { features?(features_.hello."1.0.0" deps {}) }: buildRustCrate {
      crateName = "hello";
      version = "1.0.0";
      authors = [ "John Wiegley <johnw@newartisans.com>" ];
      edition = "2018";
      src = exclude [ ".git" "target" ] ./.;
      dependencies = mapFeatures features ([
        (cratesIO.crates."chrono"."${deps."hello"."1.0.0"."chrono"}" deps)
        (cratesIO.crates."lazy_static"."${deps."hello"."1.0.0"."lazy_static"}" deps)
        (cratesIO.crates."regex"."${deps."hello"."1.0.0"."regex"}" deps)
      ]);
    };
    features_.hello."1.0.0" = deps: f: updateFeatures f (rec {
      chrono."${deps.hello."1.0.0".chrono}".default = true;
      hello."1.0.0".default = (f.hello."1.0.0".default or true);
      lazy_static."${deps.hello."1.0.0".lazy_static}".default = true;
      regex."${deps.hello."1.0.0".regex}".default = true;
    }) [
      (cratesIO.features_.chrono."${deps."hello"."1.0.0"."chrono"}" deps)
      (cratesIO.features_.lazy_static."${deps."hello"."1.0.0"."lazy_static"}" deps)
      (cratesIO.features_.regex."${deps."hello"."1.0.0"."regex"}" deps)
    ];


# end

  };

  hello = crates.crates.hello."1.0.0" deps;
  __all = [ (hello {}) ];
  deps.aho_corasick."0.7.3" = {
    memchr = "2.2.0";
  };
  deps.autocfg."0.1.4" = {};
  deps.chrono."0.4.6" = {
    num_integer = "0.1.41";
    num_traits = "0.2.8";
    time = "0.1.42";
  };
  deps.hello."1.0.0" = {
    chrono = "0.4.6";
    lazy_static = "1.3.0";
    regex = "1.1.6";
  };
  deps.lazy_static."1.3.0" = {};
  deps.libc."0.2.58" = {};
  deps.memchr."2.2.0" = {};
  deps.num_integer."0.1.41" = {
    num_traits = "0.2.8";
    autocfg = "0.1.4";
  };
  deps.num_traits."0.2.8" = {
    autocfg = "0.1.4";
  };
  deps.redox_syscall."0.1.54" = {};
  deps.regex."1.1.6" = {
    aho_corasick = "0.7.3";
    memchr = "2.2.0";
    regex_syntax = "0.6.6";
    thread_local = "0.3.6";
    utf8_ranges = "1.0.2";
  };
  deps.regex_syntax."0.6.6" = {
    ucd_util = "0.1.3";
  };
  deps.thread_local."0.3.6" = {
    lazy_static = "1.3.0";
  };
  deps.time."0.1.42" = {
    libc = "0.2.58";
    redox_syscall = "0.1.54";
    winapi = "0.3.7";
  };
  deps.ucd_util."0.1.3" = {};
  deps.utf8_ranges."1.0.2" = {};
  deps.winapi."0.3.7" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
}
